SP_Projekt2/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'^admin/', admin.site.urls),
	url(r'^app/', include('kalkulator.urls')),	
	
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

kalkulator/urls.py
""" i created this """

from django.conf.urls import url
from . import views
from django.contrib.auth import views as auth_views
from django.contrib.staticfiles.urls import static
from django.conf import settings

urlpatterns = [
	
	# login, logout
	#url( r'^login/$',auth_views.LoginView.as_view(template_name="kalkulator/login.html"), name="login"),    	    
	#url( r'^logout/$',auth_views.LoginView.as_view(template_name="kalkulator/logout.html"), name="logout"),
        
	# registracija
	#url(r'^registracija', views.registracija, name='registracija'),     
	
    # delete		
	url(r'^delete/(?P<vrsta>\w+)/(?P<id>\d+)$', views.delete, name='delete'),
    
    # rezerviraj		
	url(r'^rezerviraj/(?P<idKomponente>\d+)/(?P<vrstaKomponente>\w+)$', views.rezerviraj, name='rezerviraj'),
    
    # odstrani		
	url(r'^odstrani/(?P<idKomponente>\d+)$', views.odstrani, name='odstrani'),
    
    # kosarica		
	url(r'^kosarica', views.kosarica, name='kosarica'),
        
    # add		
	url(r'^add/(?P<vrsta>\w+)/(?P<id>\d+)$', views.add, name='add'),
    
	# main		
	url(r'^main', views.main, name='main'), 
	 	
    # graficne
    url(r'^graficne', views.graficne, name='graficne'),
    
    # inputi
    url(r'^inputi', views.inputi, name='inputi'),
    
    # procesorji
    url(r'^procesorji', views.procesorji, name='procesorji'),
    
    # maticne
    url(r'^maticne', views.maticne, name='maticne'),           
       
    # diski
    url(r'^diski', views.diski, name='diski'),
    
    # rami
    url(r'^rami', views.rami, name='rami'),
           
    # zasloni
    url(r'^zasloni', views.zasloni, name='zasloni'),
    
    # napajalniki
    url(r'^napajalniki', views.napajalniki, name='napajalniki'),
    
    # razsiritvene
    url(r'^razsiritvene/(?P<izbrani>\w+)', views.razsiritvene, name='razsiritvene'),
    
    # razsiritvene
    url(r'^razsiritvene', views.razsiritvene, name='razsiritvene'),
    
    # tiskalniki
    url(r'^tiskalniki', views.tiskalniki, name='tiskalniki'),
        
    # kabli
    url(r'^kabli', views.kabli,  name='kabli'),
    
    # periferija
    url(r'^periferija', views.periferija,  name='periferija'), 
    
    # drugo
    url(r'^drugo', views.drugo,  name='drugo'),       
    
    # vrsteNapajalnikov
    url(r'^vrsteNapajalnikov', views.vrsteNapajalnikov, name='vrsteNapajalnikov'),
    
    # vrstePeriferije
    url(r'^vrstePeriferije', views.vrstePeriferije, name='vrstePeriferije'),
    
    # vrsteTiskalnikov
    url(r'^vrsteTiskalnikov', views.vrsteTiskalnikov, name='vrsteTiskalnikov'),
    
    # vrsteRazsiritvenih
    url(r'^vrsteRazsiritvenih', views.vrsteRazsiritvenih, name='vrsteRazsiritvenih'),
   
    # vrsteRama
    url(r'^vrsteRama', views.vrsteRama, name='vrsteRama'),
    
    # vrsteMaticnih
    url(r'^vrsteMaticnih', views.vrsteMaticnih, name='vrsteMaticnih'),
   
    # vrsteGraficnih
    url(r'^vrsteGraficnih', views.vrsteGraficnih, name='vrsteGraficnih'),
    
    # vrsteInputov
    url(r'^vrsteInputov', views.vrsteInputov, name='vrsteInputov'),
    
    # vrsteProcesorjev
    url(r'^vrsteProcesorjev', views.vrsteProcesorjev, name='vrsteProcesorjev'),
    
    # vrsteKablov
    url(r'^vrsteKablov', views.vrsteKablov, name='vrsteKablov'),
    
    # vrsteDrugo
    url(r'^vrsteDrugo', views.vrsteDrugo, name='vrsteDrugo'),
    
    # dodajInput
    url(r'^dodajInput', views.dodajInput, name='dodajInput'),
    
    # dodajPeriferijo
    url(r'^dodajPeriferijo', views.dodajPeriferijo, name='dodajPeriferijo'),
    
    # vrsteDiskov
    url(r'^vrsteDiskov', views.vrsteDiskov, name='vrsteDiskov'),
    
     # dodajGraficno
    url(r'^dodajGraficno', views.dodajGraficno, name='dodajGraficno'),
    
    # dodajProcesor
    url(r'^dodajProcesor', views.dodajProcesor, name='dodajProcesor'),
    
    # dodajMaticno
    url(r'^dodajMaticno', views.dodajMaticno, name='dodajMaticno'),      
    
    # dodajNapajalnik
    url(r'^dodajNapajalnik', views.dodajNapajalnik, name='dodajNapajalnik'),     
    
    # dodajDisk
    url(r'^dodajDisk', views.dodajDisk, name='dodajDisk'),
    
    # dodajRam
    url(r'^dodajRam', views.dodajRam, name='dodajRam'),
           
    # dodajZaslon
    url(r'^dodajZaslon', views.dodajZaslon, name='dodajZaslon'),
    
    # dodajRazsiritveno
    url(r'^dodajRazsiritveno', views.dodajRazsiritveno, name='dodajRazsiritveno'),
    
    # dodajKabel
    url(r'^dodajKabel', views.dodajKabel, name='dodajKabel'),        
    
    # dodajTiskalnik
    url(r'^dodajTiskalnik', views.dodajTiskalnik, name='dodajTiskalnik'), 
    
    # dodajDrugo
    url(r'^dodajDrugo', views.dodajDrugo, name='dodajDrugo'), 
	
    # potrditevNarocila
    url(r'^potrditevNarocila', views.potrditevNarocila, name='potrditevNarocila'), 
    
]

kalkulator/models.py
from django.db import models
from django.contrib.auth.models import User
import datetime

# Create your models here.

class Kategorija(models.Model):
    kategorija = models.CharField(max_length=20) 
    podkategorija = models.CharField(max_length=20)
    image = models.ImageField(upload_to='komponente/kategorije', default="/media/no-image.jpg")

class Mail(models.Model):
    posiljatelj = models.CharField(max_length=50)
    administrator = models.CharField(max_length=50)
    
class Komponenta(models.Model):
    ime = models.CharField(max_length=20)
    link = models.CharField(max_length=20)
    image = models.ImageField(upload_to='komponente/komponente', default="/media/no-image.jpg")
  
class Graficna(models.Model):     
    znamka = models.CharField(max_length=20)
    model = models.CharField(max_length=20)
    pomnilnik = models.CharField(max_length=20)
    vodilo = models.CharField(max_length=20)
    izhod = models.CharField(max_length=20)
    opis = models.CharField(max_length=20)
    kolicina = models.CharField(max_length=20)
    image = models.ImageField(upload_to='komponente/graficne', default="/media/no-image.jpg")
    
    def __str__(self):
        return self.znamka + ", " + self.model + ", " + self.pomnilnik + ", " + self.vodilo + ", " + self.izhod + ", " + self.opis + ", " + self.kolicina       

class Procesor(models.Model):     
    znamka = models.CharField(max_length=20)
    model = models.CharField(max_length=20)
    podnozje = models.CharField(max_length=20) 
    opis = models.CharField(max_length=20)
    kolicina = models.CharField(max_length=20)
    image = models.ImageField(upload_to='komponente/procesorji', default="/media/no-image.jpg")
    
    def __str__(self):
        return self.znamka + ", " + self.model + ", " + self.podnozje + ", " + self.opis + ", " + self.kolicina
        
class Maticna(models.Model):     
    znamka = models.CharField(max_length=20)
    model = models.CharField(max_length=20)
    podnozje = models.CharField(max_length=20)
    ram = models.CharField(max_length=20)
    graficna = models.CharField(max_length=20)
    opis = models.CharField(max_length=20)
    kolicina = models.CharField(max_length=20)
    image = models.ImageField(upload_to='komponente/maticne', default="/media/no-image.jpg")
    
    def __str__(self):
        return self.znamka + ", " + self.model + ", " + self.podnozje + ", " + self.ram + ", " + self.graficna + ", " + self.opis + ", " + self.kolicina  
    
class Napajalnik(models.Model):    
    vrsta = models.CharField(max_length=20)
    znamka = models.CharField(max_length=20)    
    moc = models.CharField(max_length=20)
    voltaza = models.CharField(max_length=20)       
    amperaza = models.CharField(max_length=20)    
    opis = models.CharField(max_length=20)
    kolicina = models.CharField(max_length=20)
    image = models.ImageField(upload_to='komponente/napajalniki', default="/media/no-image.jpg")   
    
    def __str__(self):
        return self.znamka + ", " + self.vrsta + ", " + self.moc + ", " + self.voltaza + ", " + self.amperaza + ", " + self.opis + ", " + self.kolicina

class Disk(models.Model):     
    znamka = models.CharField(max_length=20)    
    prikljucek = models.CharField(max_length=20)       
    velikost = models.CharField(max_length=20) 
    opis = models.CharField(max_length=20)
    kolicina = models.CharField(max_length=20)
    image = models.ImageField(upload_to='komponente/diski', default="/media/no-image.jpg")    
    
    def __str__(self):
        return self.znamka + ", " + self.prikljucek + ", " + self.velikost  + ", " + self.opis + ", " + self.kolicina
	
class Ram(models.Model):
    znamka = models.CharField(max_length=20)
    vrsta = models.CharField(max_length=20)
    velikost = models.CharField(max_length=20)
    opis = models.CharField(max_length=20)
    kolicina = models.CharField(max_length=20)
    image = models.ImageField(upload_to='komponente/rami', default="/media/no-image.jpg")
    
    def __str__(self):
        return self.znamka + ", " + self.vrsta + ", " + self.velikost + ", " + self.opis + ", " + self.kolicina
     
class Razsiritvena(models.Model):
    znamka = models.CharField(max_length=20)
    model = models.CharField(max_length=20) 
    vrsta = models.CharField(max_length=20)
    prikljucek = models.CharField(max_length=20)    
    opis = models.CharField(max_length=20)
    kolicina = models.CharField(max_length=20)
    image = models.ImageField(upload_to='komponente/razsiritvene', default="/media/no-image.jpg") 
    
    def __str__(self):
        return self.znamka + ", " + self.model + ", " + self.vrsta + ", " + self.prikljucek + ", " + self.opis + ", " + self.kolicina
   
class Zaslon(models.Model):
    znamka = models.CharField(max_length=20)
    model = models.CharField(max_length=20)    
    vrsta = models.CharField(max_length=20)
    velikost = models.CharField(max_length=20)
    input = models.CharField(max_length=20)
    opis = models.CharField(max_length=20)
    kolicina = models.CharField(max_length=20)
    image = models.ImageField(upload_to='komponente/zasloni', default="/media/no-image.jpg") 
    
    def __str__(self):
        return self.znamka + ", " + self.model + ", " + self.vrsta + ", " + self.velikost + ", " + self.input + ", " + self.opis + ", " + self.kolicina
    
class Kabel(models.Model):        
    vrsta = models.CharField(max_length=20)   
    opis = models.CharField(max_length=20)
    kolicina = models.CharField(max_length=20)
    image = models.ImageField(upload_to='komponente/kabli', default="/media/no-image.jpg")   
    
    def __str__(self):
        return self.vrsta + ", " + self.opis + ", " + self.kolicina
    
class Input(models.Model):   
    vrsta = models.CharField(max_length=20)
    znamka = models.CharField(max_length=20)    
    prikljucek = models.CharField(max_length=20)       
    povezava = models.CharField(max_length=20) 
    opis = models.CharField(max_length=20)
    kolicina = models.CharField(max_length=20)
    image = models.ImageField(upload_to='komponente/inputi', default="/media/no-image.jpg")  
    
    def __str__(self):
        return self.znamka + ", " + self.vrsta + ", " + self.prikljucek + ", " + self.povezava + ", " + self.opis + ", " + self.kolicina
  

class Tiskalnik(models.Model):  
    vrsta = models.CharField(max_length=20)
    tip = models.CharField(max_length=20)
    priklop = models.CharField(max_length=20)
    opis = models.CharField(max_length=20)
    kolicina = models.CharField(max_length=20)
    image = models.ImageField(upload_to='komponente/tiskalniki', default="/media/no-image.jpg")
    
    def __str__(self):
        return self.vrsta + ", " + self.tip + ", " + self.priklop + ", " + self.opis + ", " + self.kolicina
 
class Drugo(models.Model): 
    vrsta = models.CharField(max_length=20)
    ime = models.CharField(max_length=20)
    opis = models.CharField(max_length=20)
    kolicina = models.CharField(max_length=20)
    image = models.ImageField(upload_to='komponente/tiskalniki', default="/media/no-image.jpg") 
    
    def __str__(self):
        return self.vrsta + ", " + self.ime + ", " + self.opis + ", " + self.kolicina

class Periferija(models.Model): 
    vrsta = models.CharField(max_length=20)
    ime = models.CharField(max_length=20)
    opis = models.CharField(max_length=20)
    kolicina = models.CharField(max_length=20)
    image = models.ImageField(upload_to='komponente/tiskalniki', default="/media/no-image.jpg") 
    
    def __str__(self):
        return self.vrsta + ", " + self.ime + ", " + self.opis + ", " + self.kolicina
        
   

kalkulator/form_config/forms.py
from django import forms
from kalkulator.models import Graficna

# class BaseForm(forms.ModelForm):
#     def __init__(self, *args, **kwargs):
#         super(BaseForm,self).__init__(*args,**kwargs)
#         for bound_field in self:
#             if hasattr(bound_field, "field") and bound_field.field.required:
#                 bound_field.field.widget.attrs["required"] = "required"


# class GraficnaForm(BaseForm):
#     class Meta:
#         model = Graficna
#         fields = ["image"]

class ImageUploadForm(forms.Form):
    """Image upload form."""
    image = forms.ImageField()

kalkulator/templates/kalkulator/not needed anymore/PageObjects.html
{{racunii.ime}}

kalkulator/templates/kalkulator/not needed anymore/PorocilaPodrobno.html
{% extends "kalkulator/porocila.html" %}

{% block izpisStanja %}

	<br>
	Skupaj: {{ vsota }}€<br>
	-----------------------------------------<br>
	{% for vnos in vnosi %}			
		{{vnos}}  <br>
	{% endfor %}	

{% endblock %}

kalkulator/templates/kalkulator/not needed anymore/administracija.html
{% extends "kalkulator/base.html" %}

{% block main %}
	<div id="Stanje"> 
							
		<form action="AdministracijaPodrobno">	{% csrf_token %} 											
			<label>Seznam uporabnikov:</label><select name="dropdown">	
										{% for uporabnik in uporabniki %}		
											
												<option>{{uporabnik.username}}</option>	
											
										{% endfor%}																						
										</select>			
			<input type="submit" id="vpisi" value="Izbrisi">	
		</form>		
		
		<span id="tekst"></span>
		
		<div id="izpisStanja"> 								
							
			{{warning}}								
					
		</div>					
					
	</div>
{% endblock %}


<!-- 

{% if user.is_authenticated %}
      Hi {{ user.username }}!
      <a href="{% url 'logout' %}">logout</a>
    {% else %}
      <a href="{% url 'login' %}">login</a>
    {% endif %}



-->

kalkulator/templates/kalkulator/not needed anymore/dodajAdapter.html
{% extends "kalkulator/base.html" %}

{% block main %}
	<div id="Stanje"> 
					
		<form action="dodajAdapter" method="post" enctype="multipart/form-data"> {% csrf_token %} 		

			
			<label>Vrsta:</label><select name="vrsta">	
										<option>Vsi</option>
										{% for vrsta in vrste %}													
												<option>{{vrsta}}</option>												
										{% endfor%}		
										</select>	
										<input type="text" placeholder="Vpisite novo znamko" name="vrsta1">
			<label>Znamka:</label><select name="znamka">	
										<option>Vsi</option>
										{% for znamka in znamke %}													
												<option>{{znamka}}</option>												
										{% endfor%}																						
										</select>
										<input type="text" placeholder="Vpisite novo znamko" name="znamka1">
			<label>Voltaza:</label><select name="voltaza">	
										<option>Vsi</option>
										{% for voltaza in voltaze %}													
												<option>{{voltaza}}</option>												
										{% endfor%}	
										</select>	
										<input type="number" placeholder="Vpisite novo voltazo" name="voltaza1">
			<label>Amperaza:</label><select name="amperaza">	
										<option>Vsi</option>
										{% for amperaza in amperaze %}													
												<option>{{amperaza}}</option>												
										{% endfor%}	
										</select>	
										<input type="number" placeholder="Vpisite novo amperazo" name="amperaza1">							
			<label>Opis:</label><textarea rows="2" placeholder="Opis" name="opis"></textarea>
			<label>Kolicina:</label><input type="number" placeholder="Vpisite kolicino" name="kolicina">							
			<label>Slika:</label><input id="id_image" type="file" class="" name="image">		

			<input type="submit" id="vpisi" value="Vpisi">			
			
		</form>
		

		
		
		
		
		

		
		
					
	</div>
{% endblock %}
		
		
		
		
		

kalkulator/templates/kalkulator/not needed anymore/index.html
{% extends "kalkulator/base.html" %}



{% block main %}

	<div id="Vpis"> 												
				
		<form action="stanje.html"> 		
				<label>Uporabniško Ime:</label><input type="text" required>
				<label>Geslo:</label><input type="password" required>
				<input type="submit" id="gumbVpisRegistracija" value="Vpisi se">	
		</form>
		
		 <a id="VpisRegisterLink" href="registracija.html"> Še niste registrirani ? Registrirate se lahko tukaj.</a>
						
	</div>
	
	<h2>Login</h2>
	<form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Login</button>
  </form>
	
	
	
 
{% endblock %}

kalkulator/templates/kalkulator/not needed anymore/login.html
{% extends "kalkulator/base.html" %}

{% block logout %}
	 
{% endblock %}


{% block buttons %}
	 
{% endblock %}


{% block main %}
	
	<div id="Vpis"> 
		 <form method="post">
			{% csrf_token %}
			{{ form.as_p }}
			<button type="submit">Login</button>
		 </form>
		 
		<a id="VpisRegisterLink" href="../registracija"> Še niste registrirani ? Registrirate se lahko tukaj.</a>

	</div>
	
{% endblock %}

kalkulator/templates/kalkulator/not needed anymore/porocila.html
{% extends "kalkulator/base.html" %}

{% block main %}
	<div id="Porocilo"> 
	
		<form action="PorocilaPodrobno"> 		
			
			<label>Izberi racun:</label><select name="racun">	
										{% for racun in racuni %}		
											{% if user.username == racun.uporabnik.username %}
												<option>{{racun.ime}}</option>	
											{% endif %}
										{% endfor%}																						
										</select>			
			<label>Izberi kategorijo:</label><select name="kategorija">		
										<option selected>plača</option>
										<option>darilo</option>
										<option>ostali prihodki</option>
										<option>živila</option>
										<option>stroški stanovanje</option>
										<option>stroški avtomobil</option>	
										<option>ostali odhodki</option>	
										</select>
			<input type="submit" id="vpisi" value="Prikazi">	
		</form>
															
		<div id="izpisStanja"> 
			
			{% block izpisStanja %}
			
			{% endblock %}
			
			{{warning}}
			
		</div>	
		
	</div>	

{% endblock %}

kalkulator/templates/kalkulator/not needed anymore/registracija.html
{% extends "kalkulator/base.html" %}

{% block logout %}
	 
{% endblock %}

{% block buttons %}
	 
{% endblock %}

{% block main %}

	<div id="Vpis"> 
				
		<form action="registracija.html"> 	{% csrf_token %}												
				
			<label>Uporabniško ime:</label><input type="text"  name="ime">		
			<label>Geslo:</label><input type="password"  name="geslo">
			<label>Ponovno vnesite geslo:</label><input type="password" name="geslo1">	
			<label>Elektronski naslov:</label><input type="text"  name="email">
			<input type="submit" id="gumbVpisRegistracija" value="Registriraj">
									
		</form>
		<br>
		{{warning}}
		
		<a id="VpisRegisterLink" href="login"> Ste že registrirani ? Vpišete se lahko tukaj.</a>
		
		
		
	</div>
 
{% endblock %}

kalkulator/templates/kalkulator/not needed anymore/stanjePodrobno.html
{% extends "kalkulator/stanje.html" %}

{% block izpisStanja %}
		
	
	<br>
	Stanje na racunu: {{ vsota }}€<br>
	-----------------------------------------<br>
	{% for vnos in vnosi %}			
		{{vnos}}  <br>
	{% endfor %}	

		
	
{% endblock %}

kalkulator/templates/kalkulator/not needed anymore/vpisiOdhodek.html
{% extends "kalkulator/base.html" %}

{% block main %}
				
		<div id="Obrazec">
	
			<form action="VpisiOdhodekPodrobno">	{% csrf_token %} 											
					<label>Kategorija:</label><select name="kategorija"> 			
													<option selected>živila</option>
													<option>stroški stanovanje</option>
													<option>stroški avtomobil</option>													
													<option>ostali odhodki</option>														
											  </select>														  
					<label>Racun:</label><select name="racun">		
													{% for racun in racuni %}		
													{% if user.username == racun.uporabnik.username %}
													<option>{{racun.ime}}</option>	
													{% endif %}
													{% endfor%}															
					</select>
					<label>Znesek:</label><input type="text"  placeholder="Vpisite znesek" name="znesek">													
					<label>Podrobnosti:</label><textarea rows="2" placeholder="Vpisite podrobnosti odhodka" name="podrobnosti"></textarea>		
					<input type="submit" id="vpisi" value="Vpisi">	
			</form>

		
		
			<div id="izpisStanja"> 								
					
				{% block vpisOdhodka %}
				
				{% endblock %}
				
				{{warning}}
						
			</div>		
		
		</div>
			 
{% endblock %}

kalkulator/templates/kalkulator/not needed anymore/vpisiOdhodekPodrobno.html
{% extends "kalkulator/vpisiOdhodek.html" %}
		
				
{% block vpisOdhodka %}
	Odhodek uspešno vpisan!
{% endblock %}
	

kalkulator/templates/kalkulator/not needed anymore/vpisiPrihodek.html
{% extends "kalkulator/base.html" %}

{% block main %}

	<div id="Obrazec">
												
		<form action="VpisiPrihodekPodrobno"> {% csrf_token %} 	
								
			<label>Kategorija:</label><select name="kategorija">		
										<option selected>plača</option>
										<option>darilo</option>										
										<option>ostali prihodki</option>											<
										</select>								
			<label>Racun:</label><select name="racun">		
										{% for racun in racuni %}		
											{% if user.username == racun.uporabnik.username %}
												<option>{{racun.ime}}</option>	
											{% endif %}
										{% endfor%}																									
										</select>
			<label>Znesek:</label><input type="text" placeholder="Vpisite znesek" name="znesek">													
			<label>Podrobnosti:</label><textarea rows="2" placeholder="Vpisite podrobnosti prihodka" name="podrobnosti"></textarea>							
			<input type="submit" id="vpisi" value="Vpisi">			
			
		</form>
		
	
		
	<div id="izpisStanja"> 								
			
		{% block vpisPrihodka %}		
		{% endblock %}	
		
		{{warning}}
		
	</div>
					
	</div>		
 
{% endblock %}

kalkulator/templates/kalkulator/not needed anymore/vpisiPrihodekPodrobno.html
{% extends "kalkulator/vpisiPrihodek.html" %}

						
				
{% block vpisPrihodka %}
	Prihodek uspešno vpisan!
{% endblock %}
	
	
	